/**
 * Loads the committed grade-statistics dataset (generated by
 * `scripts/sync-grade-statistics.mjs` into `public/grade-statistics.json`).
 *
 * The file is served same-origin, so normal app use never depends on CheeseFork
 * or GitHub availability. Loading is best-effort: on any failure the hook
 * reports `unavailable` and the catalog keeps working with grade controls hidden.
 */
import { useEffect, useState } from 'react';
import { buildIndex, collectSemesters, type GradeStatisticsIndex } from '../domain/gradeStatistics';
import type { CourseGradeStatistics, GradeCategory } from '../domain/gradeStatistics/types';

interface RawRecord {
  semester: string;
  category: GradeCategory;
  average: number | null;
  median: number | null;
  students: number | null;
}

interface RawDataset {
  generatedAt?: string;
  source?: string;
  courses?: Record<string, RawRecord[]>;
}

export interface GradeStatisticsData {
  index: GradeStatisticsIndex;
  /** Distinct semester codes present in the dataset, newest first. */
  semesters: string[];
  generatedAt: string | null;
}

let cache: GradeStatisticsData | null = null;
let inflight: Promise<GradeStatisticsData | null> | null = null;

function datasetUrl(): string {
  const base = (import.meta.env?.BASE_URL ?? '/') as string;
  return `${base}grade-statistics.json`.replace(/\/{2,}/g, '/');
}

function buildData(raw: RawDataset): GradeStatisticsData {
  const records: CourseGradeStatistics[] = [];
  for (const [courseNumber, list] of Object.entries(raw.courses ?? {})) {
    if (!Array.isArray(list)) continue;
    for (const r of list) {
      records.push({
        courseNumber,
        semester: r.semester,
        category: r.category,
        average: r.average ?? null,
        median: r.median ?? null,
        students: r.students ?? null,
        source: 'cheesefork',
      });
    }
  }
  return {
    index: buildIndex(records),
    semesters: collectSemesters(records),
    generatedAt: raw.generatedAt ?? null,
  };
}

/** Fetch + parse the dataset once. Returns `null` on failure. */
export async function loadGradeStatistics(): Promise<GradeStatisticsData | null> {
  if (cache) return cache;
  if (inflight) return inflight;

  inflight = (async () => {
    try {
      const res = await fetch(datasetUrl());
      if (!res.ok) {
        console.warn(`[gradeStatistics] dataset unavailable: HTTP ${res.status}`);
        return null;
      }
      const raw = (await res.json()) as RawDataset;
      cache = buildData(raw);
      return cache;
    } catch (error) {
      console.warn('[gradeStatistics] failed to load dataset', error);
      return null;
    } finally {
      inflight = null;
    }
  })();

  return inflight;
}

export type GradeStatisticsStatus = 'loading' | 'ready' | 'unavailable';

export interface UseGradeStatisticsResult {
  data: GradeStatisticsData | null;
  status: GradeStatisticsStatus;
}

/** React hook: loads the dataset lazily and exposes load status. */
export function useGradeStatistics(): UseGradeStatisticsResult {
  const [state, setState] = useState<UseGradeStatisticsResult>(() =>
    cache ? { data: cache, status: 'ready' } : { data: null, status: 'loading' },
  );

  useEffect(() => {
    if (state.status === 'ready') return undefined;
    let cancelled = false;
    // `loadGradeStatistics` resolves immediately from cache when available, so
    // state is only ever updated asynchronously here (no cascading renders).
    loadGradeStatistics().then((result) => {
      if (cancelled) return;
      setState({ data: result, status: result ? 'ready' : 'unavailable' });
    });
    return () => { cancelled = true; };
  }, [state.status]);

  return state;
}
